import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import SideNav from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="w-screen h-screen">
            <div className="w-full h-14">
              <Navbar />
            </div>
            <div className="h-[calc(100vh-3.5rem)] bg-[#FFFFFF] dark:bg-[#141414] w-full flex">
              {/* Side nav */}
              <SideNav />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
