import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import Providers from "@/components/Providers";
import ChatSessionHandler from "@/components/ChatSessionHandler";
import Navbar from "@/components/Navbar";

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ChatSessionHandler>
                    <Providers>
                        <div className="relative w-screen h-screen">
                            <div className="w-full h-20">
                                <Navbar />
                            </div>
                            <div className="h-[calc(100vh-5rem)] bg-[#FFFFFF] dark:bg-[#141414] w-full">
                                {children}
                            </div>
                        </div>
                    </Providers>
                </ChatSessionHandler>
            </body>
        </html>
    );
}
